### PR TITLE
Fix datafetcher none timeout

### PR DESCRIPTION
**Pull request by MCLiii**
See issue #42

### CODE REVIEW

**Comment by TheLawrus** [comment]
if we remove the if (stop) return; line then we can also remove the stop=true line 11, and the entire method actually since stop has no other purpose

**Review by TheLawrus — CHANGES_REQUESTED** [review]
See my other comment

**Comment by MCLiii** [comment]
Few more changes, using buffer.clear() in every loop causes partial data for next packet to be wasted and cause program to think it's corrupted, the new commits addresses that and remove the usleep that's slowing down the backendprocesses.

**Review by TheLawrus — APPROVED** [review]
looks good

**Pull request merged**
