### PR TITLE
Change millisec from big endian to little endian

### PR DESCRIPTION
**Pull request by MCLiii**
All our data in the byte array is in little endian except milliseconds.

### CODE REVIEW

**Comment by jrvollmer** [comment]
@MCLiii, in addition to the change here, we're going to need to change [the endianness in `api.js`](https://github.com/badgerloop-software/chase-car-dashboard/blob/main/Backend/src/routes/api.js#L499) and [the endianness in `process_recorded_data.py`](https://github.com/badgerloop-software/chase-car-dashboard/blob/main/Backend/src/routes/process_recorded_data.py#L162) in `chase-car-dashboard`. Once a PR for those changes is good to go, I'll approve it.

**Comment by MCLiii** [comment]
PR is up in chase-car-dashboard

**Comment by jrvollmer** [comment]
@MCLiii, lgtm. Once https://github.com/badgerloop-software/chase-car-dashboard/pull/63 or https://github.com/badgerloop-software/chase-car-dashboard/pull/64 is pushed through and the endianness is changed on `chase-car-dashboard/main`, I'll approve this

**Comment by jrvollmer** [comment]
@MCLiii, given how different the architecture on `main` has become, I would just go on this branch, run `git reset --hard origin/main`, make the necessary LE changes to `ethernet_sim/main.py` and `backendprocesses.cpp`, and force push the new state of this branch.

**Comment by MCLiii** [comment]
@jrvollmer Little endian yo

**Review by jrvollmer — APPROVED** [review]
LGTM

**Pull request merged**
